"""empty message

Revision ID: 65eaf1492f19
Revises: 4aac914a0c6d
Create Date: 2023-12-14 17:38:40.653392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65eaf1492f19'
down_revision = '4aac914a0c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_and_beverage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Float(), nullable=True))

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('subtotal', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('subtotal')
        batch_op.drop_column('item_price')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    with op.batch_alter_table('food_and_beverage', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
