"""empty message

Revision ID: 8c0019ec58b4
Revises: 65eaf1492f19
Create Date: 2023-12-14 17:44:49.362280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c0019ec58b4'
down_revision = '65eaf1492f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('subtotal')
        batch_op.drop_column('item_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_price', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('subtotal', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
